//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInformation
    {
        public string Name { get; set; }
        public int EmployeeId { get; set; }
        public int Age { get; set; }
        public string Designation { get; set; }
        public System.DateTime JOiningDate { get; set; }
        public System.DateTime ContactYear { get; set; }
    
        public virtual User User { get; set; }
    }
}
