//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixure
    {
        public Nullable<int> MatchDay { get; set; }
        public string Opponent { get; set; }
        public string MatchStatus { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public string Result { get; set; }
    }
}
