//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public Nullable<int> GoalScored { get; set; }
        public Nullable<int> Assist { get; set; }
        public int FitnessId { get; set; }
        public Nullable<int> SalaryId { get; set; }
        public System.DateTime JOiningDate { get; set; }
        public System.DateTime ContactYear { get; set; }
        public System.DateTime Dob { get; set; }
    
        public virtual Fitness Fitness { get; set; }
        public virtual User User { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
